matrix:
    include:
#      - os : osx
#        osx_image: xcode9.3
#        language: c++
        
      - os : linux
        language: c++
        services:
          - docker

sudo: required


before_install:
 #   - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; fi
 #   - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install gcc6; fi
 #   - if [ "$TRAVIS_OS_NAME" == "osx" ]; then CC=gcc-6; fi
 #   - if [ "$TRAVIS_OS_NAME" == "osx" ]; then CXX=g++-6; fi
 #   - if [ "$TRAVIS_OS_NAME" == "osx" ]; then wget https://github.com/google/googletest/archive/release-1.7.0.tar.gz; fi
 #   - if [ "$TRAVIS_OS_NAME" == "osx" ]; then tar xf release-1.7.0.tar.gz; fi
 #   - if [ "$TRAVIS_OS_NAME" == "osx" ]; then cd googletest-release-1.7.0; fi
 #   - if [ "$TRAVIS_OS_NAME" == "osx" ]; then cmake .; fi
 #   - if [ "$TRAVIS_OS_NAME" == "osx" ]; then make; fi
 #   - if [ "$TRAVIS_OS_NAME" == "osx" ]; then pwd; fi
 #   - if [ "$TRAVIS_OS_NAME" == "osx" ]; then sudo rsync -a ${TRAVIS_BUILD_DIR}/googletest-release-1.7.0/include/gtest /usr/local/include; fi
 #   - if [ "$TRAVIS_OS_NAME" == "osx" ]; then ls; fi
 #   - if [ "$TRAVIS_OS_NAME" == "osx" ]; then sudo rsync -a libgtest_main.a libgtest.a /usr/local/lib/; fi
 #   - if [ "$TRAVIS_OS_NAME" == "osx" ]; then cd "${TRAVIS_BUILD_DIR}"; fi
    

script:
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then docker build .; fi
  #  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew tap caskroom/cask; fi
  #  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew cask install osxfuse; fi
 
    # Run unit tests
  #  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then cd test; fi
  #  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then mkdir -p build; fi
  #  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then cd build; fi
  #  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then cmake ..; fi
  #  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then make; fi
  #  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then bin/fuse_vmu_tests; fi
