- os:
    linux
    clang


matrix:
    include:
        - os: linux
          language: cpp
          compiler: clang

        - os: linux
          language: cpp
          compiler: gcc

        - os: osx
          language: cpp
          compiler: clang

        - os: osx
          language: cpp
          compiler: gcc

before_install:
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get -qq update; fi
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get-install -y libtest-dev valgrind; fi
    - sudo wget https://github.com/google/googletest/archive/release-1.7.0.tar.gz
    - sudo tar xf release-1.7.0.tar.gz
    - cd googletest-release-1.7.0
    - sudo cmake -DBUILD_SHARED_LIBS=ON .
    - sudo make
    - sudo cp -a include/gtest /usr/include
    - sudo cp -a libgtest_main.so libgtest.so /usr/lib/
    - which valgrind
    - cd "${TRAVIS_BUILD_DIR}"

install:
    # Install LibFUSE
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install osxfuse; fi
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get-libfuse; fi

    # Run unit tests
    - cd test
    - mkdir build
    - cmake ..
    - make
    - bin/fuse_vmu_tests
