os :
    - osx
    - linux

language: c++
services:
    - docker

before_install:
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then sudo wget https://github.com/google/googletest/archive/release-1.7.0.tar.gz; fi
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then sudo tar xf release-1.7.0.tar.gz; fi
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then cd googletest-release-1.7.0; fi
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then sudo cmake -DBUILD_SHARED_LIBS=ON .; fi
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then udo make; fi
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then sudo cp -a include/gtest /usr/include; fi
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then  sudo cp -a libgtest_main.so libgtest.so /usr/lib/; fi
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then  cd "${TRAVIS_BUILD_DIR}"; fi
    

install:
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then docker build .; fi
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install osxfuse; fi
 
    # Run unit tests
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then cd test; fi
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then mkdir -p build; fi
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then cd build; fi
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then cmake ..; fi
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then make; fi
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then bin/fuse_vmu_tests; fi
